[project]
name = "cardagon-server"
version = "1.0.0"
dependencies = [
  "fastapi[standard]==0.118.0",
  "sqlmodel==0.0.25",
  "pydantic-settings==2.11.0",
]
requires-python = ">=3.13"

[tool.black]
line-length = 88
