[project]
name = "cardagon-server"
version = "1.0.0"
dependencies = [
  "fastapi[standard]==0.119.1",
  "sqlmodel==0.0.27",
  "pydantic-settings==2.11.0",
  "passlib==1.7.4",
]
requires-python = "==3.13.9"

[tool.black]
line-length = 88
